
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jinthu
 */

public class AddSubjectDetails extends javax.swing.JFrame {
    static int total=0;
    

    /**
     * Creates new form AddSubjectDetails
     */
    public AddSubjectDetails() {
        initComponents();
        jPanel2.setVisible(false);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        course = new javax.swing.JComboBox<>();
        indexNo = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        semester = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        choose1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        year = new javax.swing.JTextField();
        viewSubjects = new javax.swing.JButton();
        addCompulsorySubjects = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Subjects For Semester");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setFont(new java.awt.Font("Lato", 1, 15)); // NOI18N
        back.setForeground(new java.awt.Color(40, 162, 226));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Lato", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(145, 164, 163));
        jLabel1.setText("Index No:");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Lato", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(145, 164, 163));
        jLabel2.setText("Course:");

        course.setFont(new java.awt.Font("Lato", 1, 15)); // NOI18N
        course.setForeground(new java.awt.Color(145, 164, 163));
        course.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SCS", "IS" }));
        course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseActionPerformed(evt);
            }
        });

        indexNo.setFont(new java.awt.Font("Lato", 1, 15)); // NOI18N
        indexNo.setForeground(new java.awt.Color(145, 164, 163));

        reset.setBackground(new java.awt.Color(40, 162, 226));
        reset.setFont(new java.awt.Font("Lato", 1, 15)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        save.setBackground(new java.awt.Color(255, 255, 255));
        save.setFont(new java.awt.Font("Lato", 1, 15)); // NOI18N
        save.setForeground(new java.awt.Color(40, 162, 226));
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Lato", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(145, 164, 163));
        jLabel12.setText("Semester:");

        semester.setFont(new java.awt.Font("Lato", 1, 15)); // NOI18N
        semester.setForeground(new java.awt.Color(145, 164, 163));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Lato", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(145, 164, 163));
        jLabel3.setText("Subject Code:");

        choose1.setFont(new java.awt.Font("Lato", 1, 15)); // NOI18N
        choose1.setForeground(new java.awt.Color(145, 164, 163));
        choose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choose1ActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Lato", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(145, 164, 163));
        jLabel4.setText("Year:");

        year.setForeground(new java.awt.Color(145, 164, 163));

        viewSubjects.setBackground(new java.awt.Color(255, 255, 255));
        viewSubjects.setFont(new java.awt.Font("Lato", 1, 15)); // NOI18N
        viewSubjects.setForeground(new java.awt.Color(40, 162, 226));
        viewSubjects.setText("View Optional Subjects");
        viewSubjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSubjectsActionPerformed(evt);
            }
        });

        addCompulsorySubjects.setBackground(new java.awt.Color(40, 162, 226));
        addCompulsorySubjects.setFont(new java.awt.Font("Lato", 1, 15)); // NOI18N
        addCompulsorySubjects.setForeground(new java.awt.Color(255, 255, 255));
        addCompulsorySubjects.setText("Add Compulsory Subjects");
        addCompulsorySubjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCompulsorySubjectsActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Lato", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(145, 164, 163));
        jLabel5.setText("Add Optional Subjects");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        table.setFont(new java.awt.Font("Lato", 1, 15)); // NOI18N
        table.setForeground(new java.awt.Color(145, 164, 163));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Id", "Name", "Credit", "Semester No"
            }
        ));
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(course, 0, 212, Short.MAX_VALUE)
                                    .addComponent(indexNo)
                                    .addComponent(semester)
                                    .addComponent(year)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(viewSubjects)
                                .addGap(28, 28, 28)
                                .addComponent(addCompulsorySubjects)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(save)
                        .addGap(36, 36, 36)
                        .addComponent(reset))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(choose1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(back)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(indexNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(semester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(viewSubjects)
                                    .addComponent(addCompulsorySubjects)))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addComponent(jLabel5)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(choose1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(234, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(save)
                            .addComponent(reset))
                        .addGap(171, 171, 171))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.hide();
        UndergraduateSubjectDetails student = new UndergraduateSubjectDetails();
        student.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3308/nsbm","root","123456");
            
            String query1 = "insert into bachelorsubject(indexNo,title,result,gpa,courseid,semester)values(?,?,?,?,?,?)";
            
            PreparedStatement pst = con.prepareStatement(query1);
            pst.setString(1,indexNo.getText().toUpperCase());
            pst.setString(6,semester.getText());
            pst.setString(2,choose1.getText().toUpperCase());
            pst.setString(4,"0.0");
            pst.setString(3,"");
            String study;
            study = course.getSelectedItem().toString().toUpperCase();
            pst.setString(5,study);
            pst.executeUpdate();
            int fee = 0;
            
            String query3 = "select payment from bachelorsemester where indexno='"+indexNo.getText().toUpperCase()+"' and number='"+semester.getText()+"'";
            Statement st = con.createStatement();
            ResultSet rs1 = st.executeQuery(query3);
            if(rs1.next()){
                fee = rs1.getInt("payment");
            }
            
            
            String query2 = "select sum(fees) as total from subject where title='"+choose1.getText().toUpperCase()+"'";
            
            ResultSet rs = st.executeQuery(query2);
                
                if(rs.next()){
                    fee += rs.getInt("total");
                }
                
            String query4 = "update bachelorsemester set payment=? where indexno='"+indexNo.getText().toUpperCase()+"'";
            PreparedStatement pst3 = con.prepareStatement(query4);
            pst3.setInt(1,fee);
            
            
            pst3.executeUpdate();
            
            
            
            
            JOptionPane.showMessageDialog(null,"Subjects Added Successfully!");
        }
        catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_saveActionPerformed

    private void viewSubjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSubjectsActionPerformed
        jPanel2.setVisible(true);
        ArrayList<OptionalSubject> user = new ArrayList<>();
        
        
        
        
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3308/nsbm","root","123456");
                String study;
                study = course.getSelectedItem().toString().toUpperCase();
                String query1 = ("select title,name,credit,semesterno from subject where semesterno="+semester.getText()+" and courseid='"+study+"' and type='optional'");
            
            
             
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery(query1);
            
                while(rs.next()){
                    OptionalSubject subject = new OptionalSubject(rs.getString("title"),rs.getString("name"),rs.getInt("credit"),rs.getInt("semesterno"));
                    user.add(subject);
                }//adding every subjects
                DefaultTableModel model = (DefaultTableModel)table.getModel();
                Object[] row = new Object[4];
                for(int i=0;i<user.size();i++){
                    row[0] = user.get(i).getTitle();
                    row[1] = user.get(i).getName();
                    row[2] = user.get(i).getCredit();
                    row[3] = user.get(i).getSemesterNo();
                    model.addRow(row);
                }
            
            }
        
            catch(Exception e){
                 JOptionPane.showMessageDialog(null,e);
            }
        
    }//GEN-LAST:event_viewSubjectsActionPerformed

    private void choose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choose1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choose1ActionPerformed

    private void addCompulsorySubjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCompulsorySubjectsActionPerformed
        try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3308/nsbm","root","123456");
            
                String query = "insert into bachelorsubject(indexno,title,result,gpa,courseid,semester)select semesterno,title,credit,semesterno,courseid,semesterno from subject where semesterno=? and courseid=? and type='compulsory'";
                PreparedStatement pst1 = con.prepareStatement(query);
                pst1.setString(1,semester.getText());
                String study;
                study = course.getSelectedItem().toString().toUpperCase();
                pst1.setString(2,study);
                pst1.executeUpdate();
            
            
                String query3 = "update bachelorsubject set indexno=?,gpa=? where indexno=?";
                PreparedStatement pst3 = con.prepareStatement(query3);
                pst3.setString(1,indexNo.getText().toUpperCase());
                pst3.setString(2,"0.0");
                pst3.setString(3,semester.getText());
            
                pst3.executeUpdate();
                
                String query2 = "select sum(fees) as total from subject where semesterno="+Integer.parseInt(semester.getText())+" and type='compulsory'";
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery(query2);
                int fees = 0;
                if(rs.next()){
                    fees = rs.getInt("total");
                 
                }
                
                String query4 = "insert into bachelorsemester(indexno,number,payment,gpa) values(?,?,?,?)";
                PreparedStatement pst4 = con.prepareStatement(query4);
                pst4.setString(1,indexNo.getText().toUpperCase());
                pst4.setString(2,semester.getText());
                pst4.setInt(3,fees);
                pst4.setDouble(4,0.0);
                pst4.executeUpdate();
                
                
                
                
                JOptionPane.showMessageDialog(null,"Compulsory Subjects for Semester "+semester.getText()+" has been added!!!");
                
            }
            catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_addCompulsorySubjectsActionPerformed

    private void courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        indexNo.setText("");
        semester.setText("");
        
        year.setText("");
        choose1.setText("");
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSubjectDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSubjectDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSubjectDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSubjectDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSubjectDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCompulsorySubjects;
    private javax.swing.JButton back;
    private javax.swing.JTextField choose1;
    private javax.swing.JComboBox<String> course;
    private javax.swing.JTextField indexNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton reset;
    private javax.swing.JButton save;
    private javax.swing.JTextField semester;
    private javax.swing.JTable table;
    private javax.swing.JButton viewSubjects;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
