/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jinthu
 */
public class AdminMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public AdminMainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        studentDetails = new javax.swing.JButton();
        lecturerDetails = new javax.swing.JButton();
        instructorDetails = new javax.swing.JButton();
        adminDetails = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Home Page");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        studentDetails.setBackground(new java.awt.Color(40, 162, 226));
        studentDetails.setFont(new java.awt.Font("Lato", 1, 15)); // NOI18N
        studentDetails.setForeground(new java.awt.Color(255, 255, 255));
        studentDetails.setText("Student Menu");
        studentDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentDetailsActionPerformed(evt);
            }
        });

        lecturerDetails.setBackground(new java.awt.Color(40, 162, 226));
        lecturerDetails.setFont(new java.awt.Font("Lato", 1, 15)); // NOI18N
        lecturerDetails.setForeground(new java.awt.Color(255, 255, 255));
        lecturerDetails.setText("Lecturer Menu");
        lecturerDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecturerDetailsActionPerformed(evt);
            }
        });

        instructorDetails.setBackground(new java.awt.Color(40, 162, 226));
        instructorDetails.setFont(new java.awt.Font("Lato", 1, 15)); // NOI18N
        instructorDetails.setForeground(new java.awt.Color(255, 255, 255));
        instructorDetails.setText("Instructor Menu");
        instructorDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructorDetailsActionPerformed(evt);
            }
        });

        adminDetails.setBackground(new java.awt.Color(40, 162, 226));
        adminDetails.setFont(new java.awt.Font("Lato", 1, 15)); // NOI18N
        adminDetails.setForeground(new java.awt.Color(255, 255, 255));
        adminDetails.setText("Admin Menu");
        adminDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminDetailsActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setFont(new java.awt.Font("Lato", 1, 15)); // NOI18N
        back.setForeground(new java.awt.Color(40, 162, 226));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(instructorDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(lecturerDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studentDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adminDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(216, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(studentDetails)
                .addGap(27, 27, 27)
                .addComponent(lecturerDetails)
                .addGap(32, 32, 32)
                .addComponent(instructorDetails)
                .addGap(28, 28, 28)
                .addComponent(adminDetails)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentDetailsActionPerformed
        this.hide();
        StudentSelection student = new StudentSelection();
        student.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_studentDetailsActionPerformed

    private void lecturerDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecturerDetailsActionPerformed
        this.hide();
        LectureDetails lecturer = new LectureDetails();
        lecturer.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_lecturerDetailsActionPerformed

    private void instructorDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructorDetailsActionPerformed
        this.hide();
        InstructorDetails instructor = new InstructorDetails();
        instructor.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_instructorDetailsActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.hide();
        Login log = new Login();
        log.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void adminDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminDetailsActionPerformed
        this.hide();
        AdminMenu admin = new AdminMenu();
        admin.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_adminDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminDetails;
    private javax.swing.JButton back;
    private javax.swing.JButton instructorDetails;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lecturerDetails;
    private javax.swing.JButton studentDetails;
    // End of variables declaration//GEN-END:variables
}
